spring:
  application:
    name: elastic-query-service-reactive
  profiles:
    active: elastic_query_reactive
  config:
    import: "optional:configserver:http://localhost:8888"

logging:
  config: "classpath:log4j2-common.xml"