server:
  port: 8184
  servlet:
    context-path: /elastic-query-web-client

elastic-query-web-client:
  webclient:
    connect-timeout-ms: 10000
    read-timeout-ms: 10000
    write-timeout-ms: 10000
    max-in-memory-size: 10485760 # 10 MB
    content-type: "application/json"
    accept-type: "application/json"
    base-url: "http://elastic-query-service/elastic-query-service/documents"

spring:
  thymeleaf:
    cache: false

user-config:
  username: test
  password: '{bcrypt}$2a$12$lONUZ9zZT/HeRCLYWTHl.eoIKi5VqRl2dR/xHxCaYCi2qsKzssBuy' # test1234
  roles: USER