name: elasticsearch-cluster
services:
  elastic-1:
    image: elasticsearch:9.0.2
    container_name: elastic-1
    environment:
      - node.name=elastic-1
      - cluster.name=es-twitter-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - .\volumes\elastic\data-1:/usr/share/elasticsearch/data

volumes:
  data-1: